commonMetaLabels:
  origin_prometheus: "prometheus-server-1"

server:
  persistentVolume:
    enabled: true
    storageClass: openebs-loki-localpv
    accessModes:
      - ReadWriteOnce
    size: 8Gi

alertmanager:
  enabled: true
  persistence:
    enabled: true
    storageClass: openebs-loki-localpv
    accessModes:
      - ReadWriteOnce
    size: 2Gi
