ui:
  enabled: true

server:
  dataStorage:
    storageClass: ""
  auditStorage:
    storageClass: ""
  ha:
    enabled: false
    raft:
      enabled: false
      setNodeId: true
      config: |
        cluster_name = "vault-integrated-storage"
        storage "raft" {
           path    = "/vault/data/"
        }
        
        listener "tcp" {
           address = "[::]:8200"
           cluster_address = "[::]:8201"
           tls_disable = "true"
        }
        service_registration "kubernetes" {}
